"""Добавлено поле user_id в таблицу transactions

Revision ID: 4de7645b1297
Revises: 41e3a99b04b7
Create Date: 2024-08-21 09:32:21.250634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4de7645b1297'
down_revision: Union[str, None] = '41e3a99b04b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
